# Generated by Django 2.1.7 on 2019-03-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='游戏中文名')),
                ('foreign_name', models.CharField(max_length=50, verbose_name='游戏外文名')),
                ('language', models.CharField(max_length=256, verbose_name='游戏语言')),
                ('tags', models.CharField(max_length=256, verbose_name='游戏标签')),
                ('company', models.CharField(max_length=40, verbose_name='制作公司')),
                ('type', models.CharField(max_length=20, verbose_name='游戏类型')),
                ('desc', models.TextField(verbose_name='游戏简介')),
            ],
        ),
    ]
